name: Build unsigned iOS .ipa from HTML

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name"
        required: true
        default: "MyHTMLApp"
      html_file:
        description: "HTML filename (index.html)"
        required: true
        default: "index.html"

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Prepare Capacitor project
        run: |
          npm init -y
          npm install @capacitor/cli @capacitor/core @capacitor/ios
          mkdir -p www
          echo "<html><body><h1>Hello iOS</h1></body></html>" > www/index.html
          APP_NAME="${{ github.event.inputs.app_name }}"
          PACKAGE_ID="com.${{ github.actor }}.${{ github.event.inputs.app_name }}"
          npx cap init "$APP_NAME" "$PACKAGE_ID" --web-dir=www

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Create iOS platform manually if needed
        run: |
          npx cap add ios || true
          # иногда cap add ios падает до создания ios/App — создаём вручную
          if [ ! -d ios/App ]; then
            mkdir -p ios/App
            cd ios/App
            echo 'platform :ios, "16.0"' > Podfile
            echo 'target "App" do
  use_frameworks!
  use_modular_headers!
end' >> Podfile
            cd ../..
          fi
          ls -R ios || true

      - name: Patch Podfile target (force iOS 16.0)
        run: |
          if [ -f ios/App/Podfile ]; then
            sed -i '' 's/platform :ios.*/platform :ios, "16.0"/' ios/App/Podfile || true
          fi
          cat ios/App/Podfile

      - name: Install Pods
        run: |
          cd ios/App
          pod repo update
          pod install --verbose

      - name: Build unsigned .app
        run: |
          cd ios/App
          npx cap sync ios || true
          xcodebuild -workspace App.xcworkspace -scheme App -sdk iphoneos -configuration Release \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build

      - name: Package .ipa manually
        run: |
          cd ios/App
          mkdir -p Payload
          cp -R build/Release-iphoneos/App.app Payload/
          zip -r MyApp_unsigned.ipa Payload
          mkdir -p build/ipa
          mv MyApp_unsigned.ipa build/ipa/

      - name: Upload unsigned .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/App/build/ipa/MyApp_unsigned.ipa
          if-no-files-found: error
          retention-days: 7
